### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by bwanaaa** [typpo/gaia#1]
I assume you used python 2 because with my default python 3.6 install I got 'print' errors. Fixed that but then got this:

`python convert.py
Processing data/TgasSource_000-000-000.csv.gz ...

Traceback (most recent call last):

  File "convert.py", line 83, in <module>
    main()

  File "convert.py", line 49, in main
    for row in reader:

  File "/Users/me/anaconda3/lib/python3.6/csv.py", line 111, in __next__
    self.fieldnames
  File "/Users/me/anaconda3/lib/python3.6/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)`

with python2 it runs fine.

**Comment by typpo** [comment]
You're right, it's made for Python 2.7.  I'd accept a pull request to fix the compatibility issues, but for now I'll make a note in the README.
